### PR TITLE
a batch of fixes

### PR DESCRIPTION
**Pull request by este-rs**
(I *have* run tests.)

### CODE REVIEW

**Comment by eaburns** [comment]
Generally looks good. Thanks!

Do you mind cleaning up with some squashing?
I think you can just squash the two MU-related commits into one. Also, instead of having a fee cleanup commits at the end to gofmt and make gok.sh happy, mind squashing those changes into the relevant commits?

**Comment by este-rs** [comment]
Done. (I didn't know there was such a thing as `git rebase` before… what a wondrous feature!)

**Comment by este-rs** [comment]
Hang on for a while there… I'm added as a contributor in this repo. Would you mind if I started developing stuff & things on a separate branch?

**Comment by eaburns** [comment]
Sure  No problem.

**Comment by este-rs** [comment]
(although that would require you to merge first!)

**Comment by eaburns** [comment]
Hmm. I'm confused  Why do I need to merge this in order for you to create a separate branch? You should be able to create it locally and use `git push --set-origin` without me merging this right?

If not, probably it's best to do a quick rebase of this with the fixes I suggest, then I can merge and you create a new branch.

**Comment by este-rs** [comment]
I indeed could work independently of you.
I think I gave you write permissions to my fork, so if you wish to add your fixes, please do so.

**Comment by eaburns** [comment]
That's not what I was suggesting :-)
I just saying that I think you can create a fork on this repo without me first merging this.

If you feel like I'm a blocker, however, it's fine to work independently, but it's also nice to have one repo.

**Comment by este-rs** [comment]
Are you suggesting that I should push the fixes I made so far to a branch and continue from there or stay in my fork?

**Comment by eaburns** [comment]
You said
> Would you mind if I started developing stuff & things on a separate branch?

So I thought that is what you were suggesting. However you prefer is fine. I was just suggesting a couple of squashes and one comment about changing spaces to tabs for consistency.

If you prefer, I don't feel so strongly opinioned about it; if you say the word, I'll merge this as-is. However, if it's easy (and I think this should be), I prefer the commit history be cleaned up.

**Comment by este-rs** [comment]
But I have done the squashing already…

**Comment by eaburns** [comment]
Oh. The  don't do it again! Sorry, I'm just on my phone doing this.

**Comment by eaburns** [comment]
Thanks. Sorry about the confusion.

**Comment by este-rs** [comment]
kủaq kỉe ka

**Comment by eaburns** [comment]
Re-reading, it looks like I missed the whole message where you said you did the rebase. I'll be more observant next time. Sorry again.

**Comment by este-rs** [comment]
No problem! I'll be fixing the leftover issues and updating the code to reflect the official™ changes in the language. (And I'll probably be writing an extension for serial predicate processing in the future.) See you soon.

**Comment by eaburns** [comment]
Wonderful! Thanks for your work on this. Hopefully I'll be back to help sometime, but the longer it takes me to find the time, the farther behind I fall. This will help keep me apprised of the latest changes.

**Pull request merged**
